version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
